name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  report-card:
    name: Report card
    uses: ./.github/workflows/reportcard.yml
    with:
      config: examples/config.toml
